name = "TechnoCraft: Baianos"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "194616b2c8f3ab8f67bbfe97aa7005787df4708093fd5ddb72ea70c91576cc21"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
