name = "TechnoCraft: Baianos"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8685ff2517d4733e6b8ae3d1e085457daa8f7a9cd7c2faf624c02061d3e558d2"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
