name = "TechnoCraft: Baianos"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "931f04a841b68698b85df14a95292205a179f5d0414b79ddd903aefa11e53695"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
