name = "TechnoCraft: Baianos"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73b13c4c0ae4c28622f420d83325c9fc43afc5727d05fc4e3204a877127e9ce1"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
