name = "TechnoCraft: Baianos [SERVER]"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37e40c58b2b7c549745865169cd060733245a204b34867bbc1ca22706b033b11"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
