name = "TechnoCraft: Baianos [SERVER]"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a54299c9e60b9f1edbdab04244ca9c1bc782712d9ba0a440222f281caaa08f2"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
