name = "TechnoCraft: Baianos [SERVER]"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e86bc846aa96ee746aebd4dc2e1de7150e9a7636711857323adc97375d368d11"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
