name = "TechnoCraft: Baianos [SERVER]"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f0a8dc902254cdc892cca81a8113b013a37142f130149f66a42eeb622c085b8"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
